services:
  trading-alarm-clock:
    build: ./docker
    container_name: trading-alarm-clock
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
      - /home/hattori/.config/pulse/cookie:/home/node/.config/pulse/cookie:ro
    working_dir: /app
    tty: true
    stdin_open: true
    user: node
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NO_AT_BRIDGE=1
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PULSE_COOKIE=/home/node/.config/pulse/cookie
      - TZ=Asia/Tokyo
    network_mode: host
    privileged: true
    # X11 for mac 
    extra_hosts:
      - "host.docker.internal:host-gateway"
